### PR TITLE
Fixed failed to inject X1nput*.dll when the dll file path includes non-english characters.

### PR DESCRIPTION
**Pull request by onenowy**
Some languages consume 3 bytes per character. char type is not enough for these languages.

### CODE REVIEW

**Comment by araghon007** [comment]
Oh oops, that's what I get for assuming stuff when working with strings. Do the P/Invoke functions work fine with multibyte characters? I'd assume so since it takes in bytes directly, but just want to double check.

Also I don't really like using default anything when it comes to .NET, especially when it comes to globalization/localization because they always mess it up. Would using Encoding.Unicode suffice?

**Comment by araghon007** [comment]
I have realized looking at the code now that I contradicted my old self when talking about Encoding.Default, but I'm a better person now! I've also realized that I haven't done any sort of error checking in the function, so good job for finding this mistake.

**Comment by araghon007** [comment]
Alright, I have figured it out. I'm gonna merge this pull request and do some changes after. Thank you.

**Comment by onenowy** [comment]
Thanks, I'm glad to help.

**Pull request merged**
